package main

import (
	"net/http"
	"io/ioutil"
	"encoding/json"
	"log"

)

type AutoGenerated struct {
	Entries []struct {
		Latitude    string `json:"latitude"`
		Name        string `json:"name"`
		Adressenavn string `json:"adressenavn"`
		Longitude   string `json:"longitude"`
	} `json:"entries"`
	Page  int `json:"page"`
	Pages int `json:"pages"`
	Posts int `json:"posts"`
}

func main()  {
	http.HandleFunc("/1", Web1)
	http.ListenAndServe(":8080", nil)
}

func Web1(w http.ResponseWriter, r *http.Request) {

	url := "https://hotell.difi.no/api/json/stavanger/utsiktspunkt"

	result, _ := http.Get(url)

	body, _ := ioutil.ReadAll(result.Body)

	data := []AutoGenerated{}
	err := json.Unmarshal(body, &data)
	if err != nil {
		log.Print(err)

		//w.Write(data)


		//xp := []Utsiktpunkt{}

		/**
	for i, v := range autogenerated{
			fmt.Println(i, v)
			fmt.Println(v.Latitude)
			fmt.Println(v.Name)
			fmt.Println(v.Adressenavn)
			fmt.Println(v.Longitude)
			fmt.Println("_______________")
		}
	}*/

	}
}